# Linux instructions from: https://forum.qt.io/topic/50340/installing-qt-5-4-dev-packages-in-travis-ci/16
# TODO: Add support for macOS builds

sudo: required
dist: trusty

before_install:
#  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
  - sudo apt-get update -qq

install:
#  - sudo apt-get -y install qt55[QTPACKAGE] libqt5serialport5-dev
  - sudo apt-get -y install qt57[QTPACKAGE] qt57serialport libusb-1.0-0-dev

script:
#  - source /opt/qt55/bin/qt55-env.sh
  - source /opt/qt57/bin/qt57-env.sh
  - cd PatternPaint
  - qmake -config release PREFIX=/app
  - make -j7
#  - sudo make install # Why does it not seem to work?
#  - find /app # Why is there nothing?
#  - sudo chown -R $USER /app
  - icns2png images/patternpaint.icns -x
  - cp patternpaint_256x256x32.png patternpaint.png
  - cd ..
  - find PatternPaint/
  - wget -c https://github.com/probonopd/linuxdeployqt/releases/download/1/linuxdeployqt-1-x86_64.AppImage -O linuxdeployqt
  - chmod a+x linuxdeployqt
  - unset LD_LIBRARY_PATH # Remove too old Qt from the search path; TODO: Move inside the linuxdeployqt AppImage

  - ./linuxdeployqt PatternPaint/PatternPaint -qmldir=PatternPaint/ -bundle-non-qt-libs || true
  - ./linuxdeployqt PatternPaint/PatternPaint -qmldir=PatternPaint/ -appimage

branches:
  except:
    - /^(?i:continuous)$/ # Do not build tags that we create when we upload to GitHub Releases
